#!/usr/bin/env bash
php /screener/ethla orderbook:get --symbol=XBTUSD \
    --f=xbtusd \
    --pf=100 \
    --pt=100000 \
    --s=5 --limit=50 \
    --l1=300 --l2=400 --l3=600 \
    --schema=discrete_levels \
    --floating=2
exit 1