#!/usr/bin/env bash
php /screener/ethla orderbook:get --symbol=XBTUSD \
    --f=xbtusd_zoom \
    --pf=7750 \
    --pt=8850 \
    --s=25 --limit=30 \
    --l1=200 --l2=300 --l3=500 \
    --schema=discrete_levels \
    --floating=2 &