#!/usr/bin/env bash
php /screener/ethla orderbook:get --symbol=XBTUSD \
    --f=xbtusd_zoom \
    --pf='auto' \
    --pt='auto' \
    --s=1 --limit=50 \
    --l1=150 --l2=200 --l3=300 \
    --schema=discrete_levels \
    --floating=2
exit 1
