#!/usr/bin/env bash
php /screener/ethla orderbook:get --symbol=ETHUSD \
    --f=ethusd \
    --pf=100 \
    --pt=300 \
    --s=5 --limit=50 \
    --l1=1000 --l2=1500 --l3=2500 \
    --schema=discrete_levels \
    --floating=2
exit 1