#!/usr/bin/env bash
php /screener/ethla orderbook:get --symbol=ETHUSD \
    --f=ethusd_zoom \
    --pf=140 \
    --pt=200 \
    --s=1 --limit=30 \
    --l1=1500 --l2=1750 --l3=2000 \
    --schema=discrete_levels \
    --floating=2 &