#!/usr/bin/env bash
php /screener/ethla orderbook:get --symbol=XRPZ19 \
    --f=xrpbtc \
    --pf=0.00001000 \
    --pt=0.00010000 \
    --s=5 --limit=50 \
    --l1=10000000000 --l2=20000000000 --l3=35000000000 \
    --schema=discrete_levels \
    --floating=2 &